### ISSUE TITLE
domain is repeated

### ISSUE THREAD

**Issue by captainwasabi** [mrlesmithjr/ansible-etc-hosts#6]
The domain is repeated in the hosts files.

these are all lxd containers

This is the playbook:

```
- hosts: all
  become: true
  vars:
    etc_hosts_add_all_hosts: true
    etc_hosts_enable_ipv6: false
    etc_hosts_static_ip: false
    etc_hosts_pri_dns_name: xyz.lan
    etc_hosts_use_ansible_ssh_host: false
    etc_hosts_use_default_ip_address: true
 
#  tasks:
#  - debug:
#      var: ansible_fqdn
#  - debug:
#      var: ansible_domain

  roles:
    - role: mrlesmithjr.etc-hosts
```
the lxd network configuration defines dns.domain as xyz.lan

the container abc has an ansible_fqdn of abc.xyz.lan

then entries in /etc/hosts are

10.0.0.2 abc.xyz.lan.xyz.lan abc
